/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b27c9f82-ab9c-4df1-a215-671500fc6a5c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ViE1LZJyW",
    "aws_user_pools_web_client_id": "7p4ftnsd7dso38qdm2n098eq1s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dex5d6eobfa3dgpern3ubw2hki.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-k6au6l2s4fdexojnmvzf4mvjga",
    "aws_content_delivery_bucket": "coffeetracker-20200902000658-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d3nfbfp79rhtct.cloudfront.net"
};


export default awsmobile;
